apiVersion: v1
kind: Service
metadata:
  name: express-test-service
  namespace: study
spec:
  type: NodePort
  selector:
    app: express-test
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007
